import { Component, inject, signal, computed, ChangeDetectionStrategy } from '@angular/core';
import { CustomerService } from '../../../core/services/customer-service';
import { CustomerPayload } from '@data/models/customer/customer.model';
import { v7 as uuidv7 } from 'uuid';
import { Router } from '@angular/router';
import { form, FormField, required, email } from '@angular/forms/signals';
import { generateCustomerCode } from '../utils/customer-utils';

interface CustomerFormModel {
  personType: 'JURIDICA' | 'NATURAL' | '';
  firstName: string;
  lastName: string;
  legalName: string;
  email: string;
  phone: string;
  dni: string;
  ruc: string;
  ce: string;
  customerCode: string;
  customerType: 'NUEVO' | 'FRECUENTE' | 'IMPRENTERO_NUEVO' | 'IMPRENTERO_FRECUENTE' | '';
}

@Component({
  selector: 'app-customers-create',
  imports: [FormField],
  templateUrl: './customers-create.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export default class CustomersCreate {
  private readonly customersService = inject(CustomerService);
  private readonly router = inject(Router);

  protected readonly loading = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly success = signal(false);
  protected readonly notesList = signal<{ key: string; value: string }[]>([]);

  // Signal Form Model
  protected readonly customerModel = signal<CustomerFormModel>({
    personType: '',
    firstName: '',
    lastName: '',
    legalName: '',
    email: '',
    phone: '+51',
    dni: '',
    ruc: '',
    ce: '',
    customerCode: '',
    customerType: '',
  });

  // Form con validadores
  protected readonly customerForm = form(this.customerModel, (schema) => {
    required(schema.phone, { message: 'Teléfono es requerido' });
    email(schema.email, { message: 'Email inválido' });
  });

  // Computed: Auto-generar código cuando hay first y last name
  protected readonly autoGeneratedCode = computed(() => {
    const { firstName, lastName, legalName, ruc, personType } = this.customerModel();
    if (firstName && lastName && personType === 'NATURAL') {
      return generateCustomerCode(firstName, lastName);
    }
    if (legalName && ruc && personType === 'JURIDICA') {
      return generateCustomerCode(legalName, ruc);
    }
    return '';
  });

  protected addNote(): void {
    this.notesList.update((notes) => [...notes, { key: '', value: '' }]);
  }

  protected removeNote(index: number): void {
    this.notesList.update((notes) => notes.filter((_, i) => i !== index));
  }

  protected updateNote(index: number, field: 'key' | 'value', value: string): void {
    this.notesList.update((notes) => {
      const newNotes = [...notes];
      newNotes[index] = { ...newNotes[index], [field]: value };
      return newNotes;
    });
  }

  protected generateCode(): void {
    const code = this.autoGeneratedCode();
    if (code) {
      this.customerForm.customerCode().value.set(code);
    }
  }

  private serializeNotes(): Record<string, string> | null {
    const notesArr = this.notesList();
    const notesObj: Record<string, string> = {};
    for (const { key, value } of notesArr) {
      if (key && key.trim()) notesObj[key.trim()] = value;
    }
    return Object.keys(notesObj).length ? notesObj : null;
  }

  private validateConditionalFields(): boolean {
    const model = this.customerModel();
    if (model.personType === 'NATURAL') {
      if (!model.firstName || !model.lastName) {
        this.error.set('Nombres y Apellidos son requeridos para persona natural');
        return false;
      }
    } else if (model.personType === 'JURIDICA') {
      if (!model.legalName) {
        this.error.set('Razón social es requerida para persona jurídica');
        return false;
      }
    } else {
      this.error.set('Debe seleccionar un tipo de persona');
      return false;
    }

    if (!model.customerType) {
      this.error.set('Debe seleccionar un tipo de cliente');
      return false;
    }

    return true;
  }

  protected async onSubmit(event: Event): Promise<void> {
    event.preventDefault();

    // Validar campos requeridos
    if (this.customerForm.phone().invalid()) {
      this.error.set('Por favor complete los campos requeridos');
      return;
    }

    // Validar email si está presente
    const emailField = this.customerForm.email();
    if (emailField.value() && emailField.invalid()) {
      this.error.set('El email ingresado no es válido');
      return;
    }

    if (!this.validateConditionalFields()) {
      return;
    }

    this.loading.set(true);
    this.error.set(null);

    const model = this.customerModel();
    const customer: CustomerPayload = {
      id: uuidv7(),
      firstName: model.firstName || '',
      lastName: model.lastName || '',
      legalName: model.legalName || null,
      email: model.email || null,
      phone: model.phone || null,
      dni: model.dni || null,
      ruc: model.ruc || null,
      ce: model.ce || null,
      personType: model.personType as 'JURIDICA' | 'NATURAL',
      customerCode: model.customerCode || null,
      customerType: model.customerType as
        | 'NUEVO'
        | 'FRECUENTE'
        | 'IMPRENTERO_NUEVO'
        | 'IMPRENTERO_FRECUENTE',
      notes: this.serializeNotes(),
    };

    try {
      await this.customersService.createCustomer(customer);
      this.success.set(true);
      setTimeout(() => this.router.navigate(['/clientes']), 800);
    } catch (e: any) {
      console.error('[CustomersCreate] Error:', e);
      this.error.set(e.message || 'Error al crear cliente');
    } finally {
      this.loading.set(false);
    }
  }
}
