-- ###################################################################
-- # POS Module
-- ###################################################################

DROP TABLE IF EXISTS sales.order_details CASCADE;
DROP TABLE IF EXISTS sales.order_status CASCADE;
DROP TABLE IF EXISTS sales.orders CASCADE;

CREATE TABLE sales.order_status
(
  order_status_id SMALLSERIAL PRIMARY KEY,
  status_name TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE sales.order_status
  ADD CONSTRAINT chk_status_name CHECK (
    status_name IS NOT NULL AND char_length(status_name) < 50
  ),
  ADD CONSTRAINT chk_description CHECK (
    description IS NULL OR char_length(description) < 200
  );

CREATE TRIGGER trg_update_order_status_timestamp
  BEFORE UPDATE ON sales.order_status
  FOR EACH ROW
  EXECUTE FUNCTION core.set_updated_at();

ALTER TABLE sales.order_status ENABLE ROW LEVEL SECURITY;

INSERT INTO sales.order_status (status_name, description) VALUES
  ('PENDIENTE', 'Orden pendiente de procesamiento.'),
  ('EN_PRODUCCION', 'Orden en proceso de producción.'),
  ('COMPLETADO', 'Orden completada y lista para entrega.'),
  ('ENTREGADO', 'Orden entregada al cliente.'),
  ('CANCELADO', 'Orden cancelada por el cliente o la tienda.');

CREATE TABLE IF NOT EXISTS sales.orders (
  id UUID PRIMARY KEY,
  shop_id UUID REFERENCES core.shops(id),
  customer_id UUID REFERENCES sales.customers(id), -- Referencia a tu tabla de clientes
  
  order_number INT GENERATED BY DEFAULT AS IDENTITY,
  status_id SMALLINT REFERENCES sales.order_status(order_status_id),
  employee_id UUID REFERENCES hr.employees(id),
  
  total_amount NUMERIC(15,4) DEFAULT 0,
  tax_amount NUMERIC(15,4) DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sales.orders
  ADD CONSTRAINT chk_total_amount CHECK (total_amount >= 0),
  ADD CONSTRAINT chk_tax_amount CHECK (tax_amount >= 0);

CREATE TRIGGER trg_update_orders_timestamp
  BEFORE UPDATE ON sales.orders
  FOR EACH ROW
  EXECUTE FUNCTION core.set_updated_at();

ALTER TABLE sales.orders ENABLE ROW LEVEL SECURITY;

-- Índice para mejorar el rendimiento en consultas por número de orden y estado
CREATE INDEX idx_orders_order_number_status ON sales.orders (order_number, status_id);

CREATE TABLE IF NOT EXISTS sales.order_details (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES sales.orders(id),
  
  -- Si es un item de inventario directo (ej: una taza)
  item_id UUID REFERENCES inventory.items(id), 
  
  description TEXT NOT NULL, -- Ej: "Banner 13oz Impreso"
  quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
  
  -- CAMPOS CRÍTICOS PARA IMPRENTA
  is_custom_size BOOLEAN DEFAULT FALSE, 
  width_mm INT,
  height_mm INT,

  unit_price NUMERIC(15,4) NOT NULL,
  subtotal NUMERIC(15,4) GENERATED ALWAYS AS (quantity * unit_price) STORED,
  
  -- Para guardar si lleva ojalillos, laminado mate, etc.
  production_notes JSONB,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sales.order_details
  ADD CONSTRAINT chk_description_length CHECK (char_length(description) <= 200),
  ADD CONSTRAINT chk_quantity CHECK (quantity > 0),
  ADD CONSTRAINT chk_width_mm CHECK (width_mm IS NULL OR width_mm > 0),
  ADD CONSTRAINT chk_height_mm CHECK (height_mm IS NULL OR height_mm > 0),
  ADD CONSTRAINT chk_unit_price CHECK (unit_price >= 0),
  ADD CONSTRAINT chk_subtotal CHECK (subtotal >= 0);

CREATE TRIGGER trg_update_order_details_timestamp
  BEFORE UPDATE ON sales.order_details
  FOR EACH ROW
  EXECUTE FUNCTION core.set_updated_at();

ALTER TABLE sales.order_details ENABLE ROW LEVEL SECURITY;

-- ###############################################################
-- Production 
-- ###############################################################
CREATE SCHEMA IF NOT EXISTS production;

DROP TABLE IF EXISTS production.jobs CASCADE;
CREATE TABLE IF NOT EXISTS production.jobs (
  id UUID PRIMARY KEY,
  order_detail_id UUID REFERENCES sales.order_details(id) NOT NULL,
  machine_id UUID REFERENCES inventory.machines(id) NOT NULL, 
  
  employee_id UUID REFERENCES hr.employees(id) NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  
  -- Aquí se registra el consumo real que afectará al Kardex
  -- material_used_id UUID REFERENCES inventory.items(id) NOT NULL,
  -- quantity_used DECIMAL(12,3) NOT NULL, -- Ej: 3.20 metros lineales
  -- waste_quantity DECIMAL(12,3) DEFAULT 0, -- Merma

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ALTER TABLE production.jobs
--   ADD CONSTRAINT chk_quantity_used CHECK (quantity_used >= 0),
--   ADD CONSTRAINT chk_waste_quantity CHECK (waste_quantity >= 0);

CREATE TRIGGER trg_update_production_jobs_timestamp
  BEFORE UPDATE ON production.jobs
  FOR EACH ROW
  EXECUTE FUNCTION core.set_updated_at();

ALTER TABLE production.jobs ENABLE ROW LEVEL SECURITY;