-- ======================================================================
-- SALES SCHEMA
-- Point of Sale: customers, orders, payments, cash sessions
-- ======================================================================

DROP SCHEMA IF EXISTS sales CASCADE;
CREATE SCHEMA IF NOT EXISTS sales;

-- ======================================================================
-- TABLES
-- ======================================================================

-- customers
CREATE TABLE sales.customers (
  id UUID PRIMARY KEY REFERENCES core.persons(id),
  customer_code TEXT UNIQUE,
  customer_type_code TEXT,
  notes JSONB DEFAULT '{}'::JSONB,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by_id UUID REFERENCES auth.users(id) NOT NULL,
  updated_by_id UUID REFERENCES auth.users(id),
  deleted_by_id UUID REFERENCES auth.users(id)
);

ALTER TABLE sales.customers
ADD CONSTRAINT chk_customers_code_format CHECK (
  customer_code IS NULL OR customer_code ~ '^[A-Za-z0-9]{1,14}$'
),
ADD CONSTRAINT chk_customers_type_code CHECK (
  customer_type_code IN ('NUEVO', 'FRECUENTE', 'IMPRENTERO_NUEVO', 'IMPRENTERO_FRECUENTE')
);

CREATE INDEX idx_sales_customers_id_deleted_at ON sales.customers(id, deleted_at);

-- order_status
CREATE TABLE sales.order_status (
  id SMALLSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sales.order_status
ADD CONSTRAINT chk_status_name CHECK (name IS NOT NULL AND char_length(name) < 50),
ADD CONSTRAINT chk_description CHECK (description IS NULL OR char_length(description) < 200);

-- orders
CREATE TABLE sales.orders (
  id UUID PRIMARY KEY,
  shop_id UUID REFERENCES core.shops(id),
  customer_id UUID REFERENCES sales.customers(id),
  employee_id UUID REFERENCES hr.employees(id),
  
  order_number INT GENERATED BY DEFAULT AS IDENTITY,
  status_id SMALLINT REFERENCES sales.order_status(id) DEFAULT 1,
  
  total_price NUMERIC(15,4) NOT NULL DEFAULT 0,
  discount NUMERIC(15,4) DEFAULT 0,
  igv NUMERIC(15,4) DEFAULT 0,
  final_amount NUMERIC(15,4) NOT NULL DEFAULT 0,
  
  advance NUMERIC(15,4) DEFAULT 0,
  remaining_balance NUMERIC(15,4) NOT NULL DEFAULT 0,
  
  payment_status TEXT NOT NULL DEFAULT 'PENDIENTE',
  fully_paid_at TIMESTAMPTZ,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at BOOLEAN DEFAULT FALSE
);

ALTER TABLE sales.orders
ADD CONSTRAINT chk_total_price CHECK (total_price >= 0),
ADD CONSTRAINT chk_discount CHECK (discount >= 0 AND discount <= total_price),
ADD CONSTRAINT chk_igv CHECK (igv >= 0),
ADD CONSTRAINT chk_final_amount CHECK (final_amount >= 0),
ADD CONSTRAINT chk_advance CHECK (advance >= 0 AND advance <= final_amount),
ADD CONSTRAINT chk_remaining_balance CHECK (remaining_balance >= 0),
ADD CONSTRAINT chk_payment_status CHECK (payment_status IN ('PENDIENTE', 'PARCIAL', 'PAGADO'));

CREATE INDEX idx_orders_order_number_status ON sales.orders(order_number, status_id);
CREATE INDEX idx_orders_payment_status ON sales.orders(payment_status) WHERE payment_status != 'PAGADO';
CREATE INDEX idx_orders_customer_status ON sales.orders(customer_id, payment_status);

-- order_details
CREATE TABLE sales.order_details (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES sales.orders(id),
  item_id UUID REFERENCES inventory.items(id),
  
  description TEXT NOT NULL,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
  unit_price NUMERIC(15,4) NOT NULL,
  
  is_custom_size BOOLEAN DEFAULT FALSE,
  width_mm DECIMAL(10,2),
  height_mm DECIMAL(10,2),
  area_mm2 NUMERIC(16,4),
  
  subtotal NUMERIC(15,4),
  
  attributes JSONB DEFAULT '{}'::JSONB,
  production_notes TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sales.order_details
ADD CONSTRAINT chk_description_length CHECK (char_length(description) <= 200),
ADD CONSTRAINT chk_quantity CHECK (quantity > 0),
ADD CONSTRAINT chk_unit_price CHECK (unit_price >= 0),
ADD CONSTRAINT chk_width_mm CHECK (width_mm IS NULL OR width_mm > 0),
ADD CONSTRAINT chk_height_mm CHECK (height_mm IS NULL OR height_mm > 0),
ADD CONSTRAINT chk_area_mm2 CHECK (area_mm2 IS NULL OR area_mm2 > 0),
ADD CONSTRAINT chk_subtotal CHECK (subtotal >= 0);

-- cash_register_sessions
CREATE TABLE sales.cash_register_sessions (
  id UUID PRIMARY KEY,
  shop_id UUID NOT NULL REFERENCES core.shops(id),
  cashier_id UUID NOT NULL REFERENCES hr.employees(id),
  
  session_number INT GENERATED BY DEFAULT AS IDENTITY,
  session_type TEXT NOT NULL DEFAULT 'PARCIAL',
  
  opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  
  opening_balance NUMERIC(15,4) NOT NULL DEFAULT 0,
  closing_balance NUMERIC(15,4),
  expected_balance NUMERIC(15,4),
  difference NUMERIC(15,4),
  
  cash_total NUMERIC(15,4) DEFAULT 0,
  card_total NUMERIC(15,4) DEFAULT 0,
  transfer_total NUMERIC(15,4) DEFAULT 0,
  digital_wallet_total NUMERIC(15,4) DEFAULT 0,
  other_total NUMERIC(15,4) DEFAULT 0,
  
  total_orders INT DEFAULT 0,
  total_payments INT DEFAULT 0,
  
  status TEXT NOT NULL DEFAULT 'ABIERTO',
  
  opening_notes TEXT,
  closing_notes TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sales.cash_register_sessions
ADD CONSTRAINT chk_session_type CHECK (session_type IN ('PARCIAL', 'FINAL')),
ADD CONSTRAINT chk_session_status CHECK (status IN ('ABIERTO', 'CERRADO')),
ADD CONSTRAINT chk_opening_balance CHECK (opening_balance >= 0),
ADD CONSTRAINT chk_closing_balance CHECK (closing_balance IS NULL OR closing_balance >= 0),
ADD CONSTRAINT chk_expected_balance CHECK (expected_balance IS NULL OR expected_balance >= 0),
ADD CONSTRAINT chk_closed_at_when_closed CHECK (
  (status = 'CERRADO' AND closed_at IS NOT NULL) OR
  (status = 'ABIERTO' AND closed_at IS NULL)
),
ADD CONSTRAINT chk_opening_notes CHECK (opening_notes IS NULL OR char_length(opening_notes) <= 500),
ADD CONSTRAINT chk_closing_notes CHECK (closing_notes IS NULL OR char_length(closing_notes) <= 500);

CREATE INDEX idx_cash_sessions_shop ON sales.cash_register_sessions(shop_id);
CREATE INDEX idx_cash_sessions_cashier ON sales.cash_register_sessions(cashier_id);
CREATE INDEX idx_cash_sessions_status ON sales.cash_register_sessions(status);
CREATE INDEX idx_cash_sessions_dates ON sales.cash_register_sessions(opened_at, closed_at);
CREATE INDEX idx_cash_sessions_type ON sales.cash_register_sessions(session_type);

-- payments
CREATE TABLE sales.payments (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES sales.orders(id) ON DELETE CASCADE,
  cash_register_session_id UUID REFERENCES sales.cash_register_sessions(id),
  
  amount NUMERIC(15,4) NOT NULL,
  payment_method TEXT NOT NULL,
  payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  transaction_reference TEXT,
  notes TEXT,
  
  received_by_id UUID REFERENCES hr.employees(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

ALTER TABLE sales.payments
ADD CONSTRAINT chk_payment_amount CHECK (amount > 0),
ADD CONSTRAINT chk_payment_method CHECK (
  payment_method IN ('EFECTIVO','YAPE','TARJETA_DEBITO','TARJETA_CREDITO','TRANSFERENCIA','DEPOSITO','DOLARES','OTRO')
),
ADD CONSTRAINT chk_transaction_reference CHECK (transaction_reference IS NULL OR char_length(transaction_reference) <= 100),
ADD CONSTRAINT chk_notes CHECK (notes IS NULL OR char_length(notes) <= 500);

CREATE INDEX idx_payments_order ON sales.payments(order_id);
CREATE INDEX idx_payments_session ON sales.payments(cash_register_session_id);
CREATE INDEX idx_payments_date ON sales.payments(payment_date);
CREATE INDEX idx_payments_method ON sales.payments(payment_method);

-- cash_expenses
CREATE TABLE sales.cash_expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cash_register_session_id UUID NOT NULL REFERENCES sales.cash_register_sessions(id) ON DELETE CASCADE,
  shop_id UUID NOT NULL REFERENCES core.shops(id),
  
  amount NUMERIC(15,4) NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  
  receipt_number TEXT,
  notes TEXT,
  
  authorized_by_id UUID REFERENCES hr.employees(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sales.cash_expenses
ADD CONSTRAINT chk_expense_amount CHECK (amount > 0),
ADD CONSTRAINT chk_expense_category CHECK (
  category IN ('OPERATIVO', 'ADMINISTRATIVO', 'MANTENIMIENTO', 'COMPRAS_MENORES', 'OTRO')
),
ADD CONSTRAINT chk_expense_description CHECK (description IS NOT NULL AND char_length(description) BETWEEN 5 AND 200),
ADD CONSTRAINT chk_receipt_number CHECK (receipt_number IS NULL OR char_length(receipt_number) <= 50),
ADD CONSTRAINT chk_expense_notes CHECK (notes IS NULL OR char_length(notes) <= 500);

CREATE INDEX idx_cash_expenses_session ON sales.cash_expenses(cash_register_session_id);
CREATE INDEX idx_cash_expenses_shop ON sales.cash_expenses(shop_id);
CREATE INDEX idx_cash_expenses_date ON sales.cash_expenses(created_at);
CREATE INDEX idx_cash_expenses_category ON sales.cash_expenses(category);

-- ======================================================================
-- VIEWS
-- ======================================================================

CREATE OR REPLACE VIEW sales.active_customers WITH (security_invoker = ON) AS
SELECT 
  c.id,
  p.first_name, p.last_name, p.legal_name,
  p.email, p.phone, p.dni, p.ruc, p.ce,
  p.person_type,
  c.customer_code, c.customer_type_code, c.notes,
  c.created_by_id,
  p.deleted_at AS person_deleted_at,
  p.updated_at AS person_updated_at,
  c.deleted_at AS customer_deleted_at,
  c.updated_at AS customer_updated_at
FROM sales.customers c
JOIN core.persons p ON c.id = p.id;

-- ======================================================================
-- TRIGGERS
-- ======================================================================

CREATE TRIGGER trg_customers_set_updated_at 
  BEFORE UPDATE ON sales.customers 
  FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

CREATE TRIGGER trg_customers_set_updated_by 
  BEFORE UPDATE ON sales.customers 
  FOR EACH ROW EXECUTE FUNCTION core.set_audit_updated_by();

CREATE TRIGGER trg_update_order_status_timestamp 
  BEFORE UPDATE ON sales.order_status 
  FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

CREATE TRIGGER trg_update_orders_timestamp 
  BEFORE UPDATE ON sales.orders 
  FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

CREATE TRIGGER trg_update_order_details_timestamp 
  BEFORE UPDATE ON sales.order_details 
  FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

CREATE TRIGGER trg_update_cash_register_sessions_timestamp 
  BEFORE UPDATE ON sales.cash_register_sessions 
  FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

CREATE TRIGGER trg_update_payments_timestamp 
  BEFORE UPDATE ON sales.payments 
  FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

CREATE TRIGGER trg_update_cash_expenses_timestamp 
  BEFORE UPDATE ON sales.cash_expenses 
  FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

-- ======================================================================
-- RLS
-- ======================================================================

ALTER TABLE sales.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.order_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.order_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.cash_register_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales.cash_expenses ENABLE ROW LEVEL SECURITY;

ALTER VIEW sales.active_customers SET (security_barrier = TRUE);

-- ======================================================================
-- SEED DATA
-- ======================================================================

INSERT INTO sales.order_status (name, description) VALUES
('PENDIENTE', 'Orden pendiente de procesamiento.'),
('EN_PRODUCCION', 'Orden en proceso de producción.'),
('COMPLETADO', 'Orden completada y lista para entrega.'),
('ENTREGADO', 'Orden entregada al cliente.'),
('CANCELADO', 'Orden cancelada por el cliente o la tienda.');
