import {
  Component,
  inject,
  signal,
  computed,
  resource,
  ChangeDetectionStrategy,
} from '@angular/core';
import { Router, ActivatedRoute, RouterModule } from '@angular/router';
import { CustomerService } from '../../../core/services/customer-service';
import { CustomerView } from '@data/models/customer/customer.model';
import { generateCustomerCode } from '../utils/customer-utils';
import { AlertModal } from '@shared/components/alert-modal/alert-modal';
import { form, FormField, required } from '@angular/forms/signals';

interface CustomerFormModel {
  personType: string;
  firstName: string;
  lastName: string;
  legalName: string;
  phone: string;
  email: string;
  dni: string;
  ce: string;
  ruc: string;
  customerCode: string;
  customerType: 'NUEVO' | 'FRECUENTE' | 'IMPRENTERO_NUEVO' | 'IMPRENTERO_FRECUENTE';
}

@Component({
  selector: 'app-customers-edit',
  imports: [RouterModule, AlertModal, FormField],
  templateUrl: './customers-edit.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export default class CustomersEditComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly customerService = inject(CustomerService);

  protected readonly saving = signal(false);
  protected readonly deleting = signal(false);
  protected readonly notesList = signal<{ key: string; value: string }[]>([]);

  protected showAlert = false;
  protected alertTitle = '';
  protected alertMessage = '';
  protected alertType: 'info' | 'warning' | 'error' | 'success' = 'info';

  protected readonly customerModel = signal<CustomerFormModel>({
    personType: '',
    firstName: '',
    lastName: '',
    legalName: '',
    phone: '',
    email: '',
    dni: '',
    ce: '',
    ruc: '',
    customerCode: '',
    customerType: 'NUEVO',
  });

  protected readonly customerForm = form(this.customerModel, (schema) => {
    required(schema.phone, { message: 'Teléfono es requerido' });
    required(schema.customerType, { message: 'Tipo de cliente es requerido' });
  });

  protected readonly customerResource = resource({
    loader: async () => {
      const id = this.route.snapshot.params['id'];
      if (!id) throw new Error('ID de cliente no proporcionado');
      const customer = await this.customerService.getCustomerById(id);
      this.populateForm(customer);
      return customer;
    },
  });

  protected readonly customer = computed(() => this.customerResource.value() ?? null);
  protected readonly loading = computed(() => this.customerResource.isLoading());
  protected readonly error = computed(() => this.customerResource.error());

  protected readonly autoGeneratedCode = computed(() => {
    const { firstName, lastName } = this.customerModel();
    if (firstName && lastName) return generateCustomerCode(firstName, lastName);
    return '';
  });

  private populateForm(customer: CustomerView): void {
    const notes: { key: string; value: string }[] = [];
    if (customer.notes && typeof customer.notes === 'object') {
      Object.entries(customer.notes).forEach(([key, value]) => {
        notes.push({ key, value: String(value) });
      });
    }
    this.notesList.set(notes);
    this.customerModel.set({
      personType: customer.personType || '',
      firstName: customer.firstName || '',
      lastName: customer.lastName || '',
      legalName: customer.legalName || '',
      phone: customer.phone || '',
      email: customer.email || '',
      dni: customer.dni || '',
      ce: customer.ce || '',
      ruc: customer.ruc || '',
      customerCode: customer.customerCode || '',
      customerType:
        (customer.customerTypeCode as
          | 'NUEVO'
          | 'FRECUENTE'
          | 'IMPRENTERO_NUEVO'
          | 'IMPRENTERO_FRECUENTE') || 'NUEVO',
    });
  }

  protected addNote(): void {
    this.notesList.update((notes) => [...notes, { key: '', value: '' }]);
  }

  protected removeNote(index: number): void {
    this.notesList.update((notes) => notes.filter((_, i) => i !== index));
  }

  protected updateNote(index: number, field: 'key' | 'value', value: string): void {
    this.notesList.update((notes) => {
      const newNotes = [...notes];
      newNotes[index] = { ...newNotes[index], [field]: value };
      return newNotes;
    });
  }

  protected generateCode(): void {
    const code = this.autoGeneratedCode();
    if (code) this.customerForm.customerCode().value.set(code);
  }

  private validateConditionalFields(): boolean {
    const model = this.customerModel();
    if (model.personType === 'NATURAL' && (!model.firstName || !model.lastName)) {
      this.showError('Nombres y Apellidos son requeridos para persona natural');
      return false;
    }
    if (model.personType === 'JURIDICA' && !model.legalName) {
      this.showError('Razón social es requerida para persona jurídica');
      return false;
    }
    return true;
  }

  private serializeNotes(): Record<string, string> | null {
    const notesArr = this.notesList();
    const notesObj: Record<string, string> = {};
    for (const { key, value } of notesArr) {
      if (key && key.trim()) notesObj[key.trim()] = value;
    }
    return Object.keys(notesObj).length ? notesObj : null;
  }

  protected async onSubmit(event: Event): Promise<void> {
    event.preventDefault();
    if (this.customerForm.phone().invalid() || this.customerForm.customerType().invalid()) {
      this.showError('Por favor complete los campos requeridos');
      return;
    }
    if (!this.validateConditionalFields()) return;

    this.saving.set(true);
    this.closeAlert();

    const customerId = this.customer()?.id;
    if (!customerId) {
      this.showError('ID de cliente no encontrado');
      this.saving.set(false);
      return;
    }

    const model = this.customerModel();
    const updateData = {
      firstName: model.firstName || undefined,
      lastName: model.lastName || undefined,
      legalName: model.legalName || undefined,
      phone: model.phone,
      email: model.email || undefined,
      dni: model.dni || undefined,
      ce: model.ce || undefined,
      ruc: model.ruc || undefined,
      customerCode: model.customerCode || undefined,
      customerType: model.customerType,
      notes: this.serializeNotes() || undefined,
    };

    try {
      await this.customerService.updateCustomer(customerId, updateData);
      this.showSuccess('Cliente actualizado correctamente');
      this.customerResource.reload();
    } catch (err: unknown) {
      console.error('[CustomersEdit] Error:', err);
      this.showError('Error al actualizar el cliente');
    } finally {
      this.saving.set(false);
    }
  }

  protected async onDelete(): Promise<void> {
    const customer = this.customer();
    if (
      !customer ||
      !confirm(
        `¿Está seguro de que desea eliminar al cliente "${customer.firstName || customer.legalName}"?`,
      )
    )
      return;

    this.deleting.set(true);
    this.closeAlert();

    try {
      await this.customerService.softDeleteCustomer(customer.id);
      this.showSuccess('Cliente eliminado correctamente');
      this.deleting.set(false);
      setTimeout(() => this.router.navigate(['/clientes']), 2000);
    } catch (err: unknown) {
      console.error('[CustomersEdit] Error:', err);
      this.showError('Error al eliminar el cliente');
      this.deleting.set(false);
    }
  }

  protected closeAlert(): void {
    this.showAlert = false;
  }

  private showError(message: string): void {
    this.alertTitle = 'Error';
    this.alertMessage = message;
    this.alertType = 'error';
    this.showAlert = true;
  }

  private showSuccess(message: string): void {
    this.alertTitle = 'Éxito';
    this.alertMessage = message;
    this.alertType = 'success';
    this.showAlert = true;
  }
}
